services:
  mongo7:
    build:
      context: ./src/config/mongodb-rs
      args:
        MONGO_VERSION: 7
    container_name: mongo7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
      MONGO_REPLICA_HOST: mongo7
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
